### ISSUE TITLE
Method Checklist

### ISSUE THREAD

**Issue by clinuxrulz** [SodiumFRP/sodium-rust#4]
- [x] Never :: Stream a (Can use ```FrpContext::new_stream_sink``` and cast to ```Stream```)
- [x] MapS :: (a → b) → Stream a → Stream b
- [x]  Snapshot* :: (a → b → c) → Stream a → Cell b → Stream c
- [x]  Merge :: Stream a → Stream a → (a → a → a) → Stream a
- [x]  Filter :: (a → Bool) → Stream a → Stream a
- [x]  SwitchS :: Cell (Stream a) → Stream a
- [ ]  Execute :: Stream (Reactive a) → Stream a
- [ ]  Updates :: Cell a → Stream a
- [x]  Value :: Cell a → T → Stream a
- [ ]  Split :: Stream [a] → Stream a
- [x]  Constant* :: a → Cell a (Can use ```FrpContext::new_cell_sink``` and cast to ```Cell```)
- [x]  Hold :: a → Stream a → T → Cell a (Can be implemented via ```FrpContext::cell_loop```)
- [x]  MapC :: (a → b) → Cell a → Cell b
- [x]  Apply :: Cell (a → b) → Cell a → Cell b (Can by implemented via ```FrpContext::lift2_cell```)
- [x]  SwitchC :: Cell (Cell a) → T → Cell a
